---
version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports: ['9200:9200']

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTICSEARCH_VERSION}
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports: ['5601:5601']
    depends_on: ['elasticsearch']

  fluent-bit:
    image: quay.io/nordstrom/fluent-bit:1.0.4
    container_name: fluent-bit
    volumes: 
      - ./log:/var/log
    command:
      - /fluent-bit/bin/fluent-bit
      - -i
      - tail
      - -p
      - Refresh_Interval=5
      - -p
      - path=/var/log/*.log
      - -o
      - es 
      - -p
      - Host=elasticsearch
      - -p
      - Port=9200
      - -p
      - Index=fluent_bit
      - -p
      - Type=logs
    depends_on: ['elasticsearch']
